# -*- coding: utf-8 -*-
"""Banknote.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MTSKA5CvACzD-hD6nhSHDNxQMdopZfux
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import numpy as np
import matplotlib.pyplot as plt

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    Conv2D,
    MaxPooling2D,
    Flatten,
    Dense,
    Dropout
)
from tensorflow.keras.preprocessing.image import (
    ImageDataGenerator,
    load_img,
    img_to_array
)

# =====================================
# DATASET PATH
# =====================================

train_dir = '/content/drive/MyDrive/Tri_Tue_Nhan_Tao/Banknote'

print("Classes found:\n")

for folder in os.listdir(train_dir):
    print(folder)

# =====================================
# IMAGE SIZE
# =====================================

img_width = 200
img_height = 200

# =====================================
# DATA AUGMENTATION
# =====================================

train_datagen = ImageDataGenerator(
    rescale=1.0 / 255,

    rotation_range=10,

    width_shift_range=0.2,
    height_shift_range=0.2,

    shear_range=0.2,

    zoom_range=0.2,

    horizontal_flip=True,

    validation_split=0.2
)

# =====================================
# TRAIN DATA
# =====================================

train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(img_width, img_height),
    batch_size=32,
    class_mode='categorical',
    subset='training'
)

# =====================================
# VALIDATION DATA
# =====================================

validation_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(img_width, img_height),
    batch_size=32,
    class_mode='categorical',
    subset='validation'
)

# =====================================
# CLASS INFO
# =====================================

num_classes = len(train_generator.class_indices)

print("\nNumber of classes:", num_classes)
print("\nClass mapping:")
print(train_generator.class_indices)

# =====================================
# CNN MODEL
# =====================================

model = Sequential([

    Conv2D(
        32,
        (3,3),
        activation='relu',
        input_shape=(img_width, img_height, 3)
    ),

    MaxPooling2D((2,2)),

    Conv2D(
        64,
        (3,3),
        activation='relu'
    ),

    MaxPooling2D((2,2)),

    Conv2D(
        128,
        (3,3),
        activation='relu'
    ),

    MaxPooling2D((2,2)),

    Flatten(),

    Dense(
        128,
        activation='relu'
    ),

    Dropout(0.5),

    Dense(
        num_classes,
        activation='softmax'
    )
])

# =====================================
# COMPILE MODEL
# =====================================

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

# =====================================
# TRAIN MODEL
# =====================================

epochs = 10

history = model.fit(
    train_generator,
    validation_data=validation_generator,
    epochs=epochs
)

# =====================================
# PLOT ACCURACY
# =====================================

plt.figure(figsize=(8,5))

plt.plot(
    history.history['accuracy'],
    label='Train Accuracy'
)

plt.plot(
    history.history['val_accuracy'],
    label='Validation Accuracy'
)

plt.title('Banknote Classification Accuracy')

plt.xlabel('Epoch')

plt.ylabel('Accuracy')

plt.legend()

plt.show()

# =====================================
# TEST IMAGE
# =====================================

test_image_path = '/content/drive/MyDrive/Tri_Tue_Nhan_Tao/test_money.jpg'

img = load_img(
    test_image_path,
    target_size=(img_width, img_height)
)

plt.imshow(img)
plt.axis('off')
plt.show()


img_array = img_to_array(img)

img_array = img_array / 255.0

img_array = np.expand_dims(
    img_array,
    axis=0
)


prediction = model.predict(img_array)

predicted_class = np.argmax(prediction)

class_labels = {
    v:k for k,v in train_generator.class_indices.items()
}

banknote_value = class_labels[predicted_class]

confidence = np.max(prediction) * 100

print("\n========== RESULT ==========")
print(f"Predicted Banknote : {banknote_value} VND")
print(f"Confidence         : {confidence:.2f}%")


model.save("banknote_model.h5")

print("\nModel saved successfully!")