# -*- coding: utf-8 -*-
"""Food recognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11GTWlp06xh9ePx7eCk4OUXSVLl8qH6AN
"""

from google.colab import drive
drive.mount('/content/drive')

# %%
import os
import numpy as np
import matplotlib.pyplot as plt

from tensorflow.keras.models import Sequential

from tensorflow.keras.layers import (
    Conv2D,
    MaxPooling2D,
    Flatten,
    Dense,
    Dropout
)

from tensorflow.keras.preprocessing.image import (
    ImageDataGenerator,
    load_img,
    img_to_array
)

train_dir = '/content/drive/MyDrive/Tri_Tue_Nhan_Tao/'
print("Classes found:\n")

for folder in os.listdir(train_dir):
    print(folder)

# %%
# %%
img_width = 200
img_height = 200


train_datagen = ImageDataGenerator(

    rescale=1.0 / 255,

    rotation_range=10,

    width_shift_range=0.2,
    height_shift_range=0.2,

    shear_range=0.2,

    zoom_range=0.2,

    horizontal_flip=True,

    validation_split=0.2
)


train_generator = train_datagen.flow_from_directory(

    train_dir,

    target_size=(img_width, img_height),

    batch_size=32,

    class_mode='categorical',

    subset='training'
)

print("\nClass labels:\n")

print(train_generator.class_indices)

validation_generator = train_datagen.flow_from_directory(

    train_dir,

    target_size=(img_width, img_height),

    batch_size=32,

    class_mode='categorical',

    subset='validation'
)


num_classes = len(train_generator.class_indices)

print("Number of classes:", num_classes)


model = Sequential([

    Conv2D(
        32,
        (3,3),
        activation='relu',
        input_shape=(img_width, img_height, 3)
    ),

    MaxPooling2D((2,2)),


    Conv2D(
        64,
        (3,3),
        activation='relu'
    ),

    MaxPooling2D((2,2)),


    Conv2D(
        128,
        (3,3),
        activation='relu'
    ),

    MaxPooling2D((2,2)),


    Flatten(),


    Dense(
        128,
        activation='relu'
    ),

    Dropout(0.5),


    Dense(
        num_classes,
        activation='softmax'
    )
])


model.compile(

    optimizer='adam',

    loss='categorical_crossentropy',

    metrics=['accuracy']
)

model.summary()


epochs = 10

history = model.fit(

    train_generator,

    validation_data=validation_generator,

    epochs=epochs
)


plt.plot(
    history.history['accuracy'],
    label='Train Accuracy'
)

plt.plot(
    history.history['val_accuracy'],
    label='Validation Accuracy'
)

plt.title('Model Accuracy')

plt.xlabel('Epoch')

plt.ylabel('Accuracy')

plt.legend()

plt.show()

test_image_path = '/content/drive/MyDrive/Tri_Tue_Nhan_Tao/Banh_mi.png'

img = load_img(
    test_image_path,
    target_size=(img_width, img_height)
)

plt.imshow(img)

plt.axis('off')

plt.show()

img_array = img_to_array(img)

img_array = img_array / 255.0

img_array = np.expand_dims(
    img_array,
    axis=0
)

prediction = model.predict(img_array)

predicted_class = np.argmax(prediction)

class_labels = {
    v:k for k,v in train_generator.class_indices.items()
}

food_name = class_labels[predicted_class]

print("\nPredicted Food:", food_name)

model.save("food_model.h5")

print("Model saved successfully!")